### PR TITLE
Fix #561

### LINKED ISSUE #561: Fix selectDocument used wrongly
Refactor showDocument => showSideDocument and fix current wrong usage.

### PR DESCRIPTION
**Pull request by haiodo**
1. Fix Panel, to not add extra overlay, it maked background too dark,
2. Allow to open tasks by click handler in presentation.
3. Refactor selectDocument to showSideDocument

Screenshot 2021-11-10 at 22 03 13

Closes #561

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

### CODE REVIEW

File: packages/ui/src/components/Popup.svelte [hunk 1]
```diff
@@ -18,11 +18,13 @@
 </script>
 
 {#each $modal as popup, i}
+  {i}
```
Comment (BykhovDenis) [inline packages/ui/src/components/Popup.svelte:21]: We need it?

**Review by BykhovDenis — APPROVED** [review]

File: packages/ui/src/components/Popup.svelte (hunk 1 above)
Comment (haiodo) [reply packages/ui/src/components/Popup.svelte:21]: Nope, let me fix:-)

Comment (haiodo) [reply packages/ui/src/components/Popup.svelte]: Fixed.
